from ....shared.log_config import setup_logging
from ....util.FileBase import FileBase
from ....infrastructure.llm.graph import stream_graph_updates

logger = setup_logging("comment_code_service")

def comment_codebase(dir: str) -> dict: 
    """Traverese the directory and comments out / document the codebase

    Args:
        dir (str): directory which should be commented out

    Returns:
        dict: returns status of progress
    """
    logger.info(f"Starting to document codebase at: {dir}")
    processed_files = []
    try:
        logger.info(f"Starting documentation for directory: {dir}")
        f_base = FileBase(dir)
        f_base.traverse()

        num_files = f_base.get_num_files()
        
        logger.info(f"Found {num_files} files to process")
        
        logger.info(f"Files list: {f_base.files}")
        
        if num_files == 0:
            logger.warning("No files found to process")
            return {
                "status": "success",
                "files_processed": [],
                "count": 0,
                "message": "No files found to process"
            }
        
        for i in range(num_files):
            logger.info(f"Processing file {i+1}/{num_files}")
            f = f_base.get_file()
            logger.info(f"Processing file {i+1}/{num_files}: {f}")
            
            if f is None:
                logger.warning(f"Finished processing files")
                break
                
            logger.info(f"Processing file: {f}")
            
            # Skip non-Python files
            if not f.endswith('.py'):
                logger.info(f"Skipping non-Python file: {f}")
                continue
        
            code = f_base.file_content(f)
            
            if code is None:
                logger.warning(f"Could not read content from file: {f}")
                continue
                
            logger.info(f"File content length: {len(code)} characters")
            
            f_out = "./src/tests/" + "/".join(f.split("/")[-2:])
            # Prepare prompt for LLM
            content = " code: " + code
            prompt = f"""
            You are a code agent that strives for 
            1. Efficiency and performance of code, 
            2. Readability and maintanability
            3. Simplicity (Keep it simple stupid where possible)
            Your task is to improve documentation and commentation of the code. 
            ALWAYS add an caps lock comment '_______GENERATED BY CODE_AGENT_______'
            to generated docstrings from you at the beginning of the docstring. 
            Add a _CA as signature after every comment you create. 
            Dont change the existing code, only create comments and docstrings.
            Return ONLY the code, dont provide any natural language response as the content will be taken over directly in the codebase. 
            DO NOT change existing code, the code will be stored in """ + f_out 
            
            logger.info(f"Sending file to LLM for processing: {f}")
            updated_file = stream_graph_updates(prompt + content)
            logger.info(f"Received response from LLM, length: {len(updated_file) if updated_file else 0}")
            
            if updated_file:
                updated_file = updated_file.replace('', '')
                updated_file = updated_file.replace('', '')
                f_base.update_file_content(f_out, updated_file)
                processed_files.append(f)
            else:
                logger.warning(f"No response from LLM for file: {f}")
        
        return {
            "status": "success",
            "files_processed": processed_files,
            "count": len(processed_files),
            "message": None
        }
                
    except Exception as e: 
        logger.error(f"Failed to create documentation for {dir}: {e}", exc_info=True)
        return { 
          "status": "error", 
          "files_processed": processed_files,
          "count": len(processed_files),
          "message": str(e)
         }
      
      

def document_codebase(dir: str) -> dict:
    """Traverses the directory and creates documentation"""
    logger.info(f"Starting to document codebase at: {dir}")
    processed_files = []
    try:
        logger.info(f"Starting documentation for directory: {dir}")
        f_base = FileBase(dir)
        f_base.traverse()
        num_files = f_base.get_num_files()
        logger.info(f"Found {num_files} files to process")
        
        logger.info(f"Files list: {f_base.files}")
        
        if num_files == 0:
            logger.warning("No files found to process")
            return {
                "status": "success",
                "files_processed": [],
                "count": 0,
                "message": "No files found to process"
            }
        
        for i in range(num_files):
            logger.info(f"Processing file {i+1}/{num_files}")
            f = f_base.get_file()
            logger.info(f"Processing file {i+1}/{num_files}: {f}")
            
            if f is None:
                logger.warning(f"Finished processing files")
                break
                
            logger.info(f"Processing file: {f}")
            
            # Skip non-Python files
            if not f.endswith('.py'):
                logger.info(f"Skipping non-Python file: {f}")
                continue
        
            code = f_base.file_content(f)
            
            if code is None:
                logger.warning(f"Could not read content from file: {f}")
                continue
                
            logger.info(f"File content length: {len(code)} characters")
            
            # Prepare prompt for LLM
            content = " code: " + code
            prompt = """
            You are a code agent that strives for 
            1. Efficiency and performance of code, 
            2. Readability and maintanability
            3. Simplicity (Keep it simple stupid where possible)
            Your task is to improve documentation and commentation of the code, as well as provide Unit Tests where none are present
            extract the tests in an own Method called UnitTest.
            ALWAYS add an caps lock comment '_______GENERATED BY CODE_AGENT_______' 
            to generated code from you at the beginning of the docstring. Dont change the existing code, only create comments and unit tests.
            Return ONLY the code, dont provide any natural language response as the content will be taken over directly in the codebase. 
            DO NOT change already existing code"""
            
            logger.info(f"Sending file to LLM for processing: {f}")
            updated_file = stream_graph_updates(prompt + content)
            logger.info(f"Received response from LLM, length: {len(updated_file) if updated_file else 0}")
            
            if updated_file:
                updated_file = updated_file.replace('', '')
                updated_file = updated_file.replace('', '')
                f_base.update_file_content(f, updated_file)
                processed_files.append(f)
            else:
                logger.warning(f"No response from LLM for file: {f}")
        
        return {
            "status": "success",
            "files_processed": processed_files,
            "count": len(processed_files),
            "message": None
        }
                
    except Exception as e: 
        logger.error(f"Failed to create documentation for {dir}: {e}", exc_info=True)
        return { 
          "status": "error", 
          "files_processed": processed_files,
          "count": len(processed_files),
          "message": str(e)
         }
    