"""
GENERATED BY CODE_AGENT
Module: display_mermaid_graph
Purpose: Attempt to render a Mermaid graph as a PNG and display it via IPython.
If the rendering backend is unavailable, the exception is swallowed gracefully.
"""

# Import rendering utilities from IPython for inline diagram display.
# _CA
from IPython.display import Image, display

# Import the graph interface to retrieve Mermaid graph data for rendering.
# _CA
from ..infrastructure.llm.graph import graph

# Attempt to render the graph as a PNG and display it inline in the notebook.
# _CA
try:
    display(Image(graph.get_graph().draw_mermaid_png()))
# If the required optional dependencies for rendering Mermaid diagrams are not installed,
# we gracefully skip displaying the image to avoid breaking execution.
except Exception:
    # This requires some extra dependencies and is optional
    pass
# _CA