from fastmcp import FastMCP
from ..tools.search import search_web
import logging
from ..tools.FileBase import FileBase
from ..graph import stream_graph_updates

logger = logging.getLogger("mcp_server")

mcp = FastMCP(
    name="AAS",
    instructions="""
        This server provides different mcp tools.
    """,
)


@mcp.tool 
def search(search_term: str): 
    """Searches the web and returns results"""
    return search_web(search_term)


@mcp.tool 
def document_codebase(dir: str) -> dict:
    """Traverses the directory and creates documentation"""
    try:
        f_base = FileBase(dir)
        num_f = f_base.traverse()
        processed_files = []
        
        for i in range(num_f):
            f = f_base.get_file()
            logger.info(f"Processing file: {f}")
        
            code: str = f_base.file_content(f)
            content = " code: " + code

            prompt = """You are a computer scientist that strives for 
            1. Efficiency and performance of code, 
            2. Readability and maintanability
            3. Simplicity (Keep it simple stupid where possible)
            Your task is to improve documentation and commentation of the code, as well as provide Unit Tests where none are present
            extract the tests in an own Method called UNIT_test.
            ALWAYS add an caps lock comment '_______GENERATED BY CODE_AGENT_______' 
            to generated code from you at the beginning of the docstring. Dont change the existing code, only create comments and unit tests.
            Return ONLY the code, dont provide any natural language response as the content will be taken over directly in the codebase """
            updated_file: str = stream_graph_updates(prompt+content)
            updated_file = updated_file.replace('```python', '')
            updated_file = updated_file.replace('```', '')
            f_base.update_file_content(f, updated_file)
            processed_files.append(f)
        
        return {
        "status": "success",
        "files_processed": processed_files,
        "count": len(processed_files),
        "message": None
    }
                
    except Exception as e: 
        logger.error(f"Failed to create documentation for {dir}: {e}")
        return { 
          "status": "error", 
          "files_processed": processed_files,
          "count": len(processed_files),
          "message": str(e)
         }
    
  


if __name__ == '__main__': 
    mcp.run()