from log_config import setup_logging
import asyncio
from dotenv import load_dotenv
from mcp_client.session_manager import chat_session

load_dotenv()

logger = setup_logging("main")

def main():
    """
    _______GENERATED BY CODE_AGENT_______
    Main entry point of the application.
    Initializes the chat session with proper logging.
    """
    logger.info("Starting chat session.")
    chat_session()
if __name__ == '__main__': 
    main()